# Market Data Service Configuration
# This file provides default configuration values
# Environment variables will override these values

server:
  port: 8083
  read_timeout: 15s
  write_timeout: 15s
  shutdown_timeout: 10s

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: hub_market_data
  sslmode: disable
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 5m

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5

grpc:
  port: 50053
  max_connection_idle: 5m
  max_connection_age: 30m
  keepalive_time: 30s
  keepalive_timeout: 10s

cache:
  ttl_minutes: 5
  enabled: true

price_oscillation:
  update_interval_seconds: 4
  oscillation_percent: 0.01
  min_price: 1.00

logging:
  level: info
  format: json
  output: stdout

environment: development

